name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install uv
        uv add --editable --dev ".[dev]"
    
    - name: Run tests
      run: |
        pytest tests/ --cov=src --cov-report=xml
      env:
        ENV: test
        DISCORD_TOKEN: ${{ secrets.TEST_DISCORD_TOKEN }}
        FOOTBALL_DATA_API_KEY: ${{ secrets.TEST_FOOTBALL_DATA_API_KEY }}
        DEEPSEEK_API_KEY: ${{ secrets.TEST_DEEPSEEK_API_KEY }}
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false